name: CI

on:
    push:
        tags:
            - v*

        branches:
            - '*'
            - '*/*'

    pull_request:
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: read

jobs:
    test:
        name: Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ macos-latest, ubuntu-latest, windows-latest ]
                go: [ '~1.19.0', '^1.23' ]
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-go@v5
                with:
                    go-version: ${{ matrix.go }}
                    check-latest: true
            -   name: Run tests
                run: make test

    test-arm:
        name: Test QEMU
        runs-on: ubuntu-latest
        strategy:
            matrix:
                distro: [ bookworm ]
                arch: [ armv6, armv7, aarch64 ]
#                go: [ '1.19.13', 'latest' ]
                go: [ '1.19.13', '1.22.6' ] # https://github.com/golang/go/issues/68976
                include:
                    -   distro: ubuntu22.04
                        arch: riscv64
                        go: '1.21.13'
                    -   distro: ubuntu22.04
                        arch: riscv64
#                        go: 'latest'
                        go: '1.22.6' # https://github.com/golang/go/issues/68976

        steps:
            -   uses: actions/checkout@v4
            -   uses: uraimo/run-on-arch-action@v2
                with:
                    distro: ${{ matrix.distro }}
                    arch: ${{ matrix.arch }}
                    install: apt update && apt install -y build-essential wget
                    run: |
                        if [ ${{ matrix.go }} = latest ]; then
                            go=$(wget -O- 'https://go.dev/dl/?mode=json' | grep -m1 version | awk -F'"' '{ print $4 }')
                        else
                            go=go${{ matrix.go }}
                        fi

                        case ${{ matrix.arch }} in
                            riscv64) filename=${go}.linux-riscv64.tar.gz ;;
                            arm*) filename=${go}.linux-armv6l.tar.gz ;;
                            *) filename=${go}.linux-arm64.tar.gz ;;
                        esac

                        wget https://golang.org/dl/$filename
                        tar -C /usr/local -xzf $filename
                        export PATH=$PATH:/usr/local/go/bin

                        go build cmd/test/test.go
                        go test --timeout 5m --count 1 ./...

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-go@v5
                with:
                    go-version: '^1.23'
            -   name: golangci-lint
                uses: golangci/golangci-lint-action@v6
